name: 'Dispatch'
description: 'Emit repository dispatch events to trigger other workflows'
branding:
  icon: 'arrow-up-circle'
  color: 'yellow'
inputs:
  token:
    description: 'The Github access token to use (i.e. secrets.GITHUB_TOKEN)'
    required: true
  repo:
    description: 'The name of the repository to dispatch the event to'
    required: true
    default: '@'
  owner:
    description: 'The owner of the repository to dispatch the event to'
    default: null
  event_type:
    description: 'The type of event to be dispatched'
    required: true
  payload:
    description: 'An optional JSON string payload to be dispatched'
runs:
  using: 'node12'
  main: 'dist/index.js'
